/**
 * Auto-generated TypeScript types for the Derby Scoreboard API.
 *
 * Source of truth: derby-scoreboard-api/models.py (Pydantic models)
 * OpenAPI spec:    http://localhost:5001/openapi.json
 *
 * To regenerate:   npm run sync:api-types
 * Do NOT edit this file by hand — changes will be overwritten.
 */

export interface SkaterPosition {
  name?: string | null;
  number?: string | null;
  /**
   * @default false
   */
  in_box?: boolean;
  /**
   * Unix epoch milliseconds when this skater entered the penalty box. None when the skater is not in the box. Overlay usage: elapsed_ms = Date.now() - box_entered_at_ms
   */
  box_entered_at_ms?: number | null;
  /**
   * Whole seconds remaining in the 30-second penalty box. None when the skater is not in the box. 0 when time has expired.
   */
  box_time_remaining_s?: number | null;
}

export interface TeamState {
  name?: string | null;
  score?: number | null;
  jam_score?: number | null;
  lead?: boolean | null;
  display_lead?: boolean | null;
  calloff?: boolean | null;
  lost?: boolean | null;
  star_pass?: boolean | null;
  /**
   * Timeouts remaining for this team (0–3)
   * @default 3
   */
  timeouts_remaining?: number;
  /**
   * Official reviews remaining (0–1)
   * @default 1
   */
  official_reviews_remaining?: number;
  /**
   * True if team retained their official review after a successful challenge
   * @default false
   */
  retained_official_review?: boolean;
  /**
   * The active jammer for this jam. When star_pass is True this is the original pivot, who received the jammer cover.
   */
  jammer?: SkaterPosition;
  /**
   * The pivot for this jam. When star_pass is True this slot holds the original jammer, who has removed their star and is now skating as a blocker. The pivot label is kept for model simplicity — consumers should check star_pass to know this skater's effective role is blocker.
   */
  pivot?: SkaterPosition;
  blocker1?: SkaterPosition;
  blocker2?: SkaterPosition;
  blocker3?: SkaterPosition;
}

export interface LiveState {
  /**
   * @default false
   */
  connected?: boolean;
  period?: number | null;
  jam?: number | null;
  jam_clock_ms?: number | null;
  jam_clock?: string | null;
  period_clock_ms?: number | null;
  period_clock?: string | null;
  jam_running?: boolean | null;
  in_jam?: boolean | null;
  /**
   * Display-oriented game state. Usually mirrors CRG's State field, but may be synthesized from clock activity for clearer downstream use. For example, when Clock(Intermission).Running is true this is returned as "Intermission" even if the raw CRG State still reads "Running".
   */
  game_state?: string | null;
  /**
   * Normalized timeout/review state. One of: team_timeout, official_timeout, official_review, timeout, or null. Resets to null when jam_running is true.
   */
  timeout_type?: string | null;
  /**
   * Timeout clock value in milliseconds as reported by CRG Clock(Timeout). None when no timeout is active.
   */
  timeout_clock_ms?: number | null;
  timeout_clock?: string | null;
  /**
   * Who owns the current timeout: '1' = team 1, '2' = team 2, 'O' = official timeout/review. None when not in a timeout.
   */
  timeout_owner?: string | null;
  /**
   * True during the lineup phase between a timeout/jam end and the next jam start (Lineup clock is running).
   * @default false
   */
  in_lineup?: boolean;
  state_age_seconds?: number | null;
  team1?: TeamState;
  team2?: TeamState;
}

export interface HealthState {
  connected: boolean;
  scoreboard_version?: string | null;
  seconds_since_update?: number | null;
}
