name: Quality Gate

# This workflow runs on all pushes and PRs to ensure code quality
# Vercel will only deploy if this workflow passes when configured properly
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  quality-gate:
    name: Quality Gate - Tests & Build
    runs-on: ubuntu-latest

    env:
      # Environment variables for better CI compatibility
      NODE_OPTIONS: --experimental-vm-modules --max-old-space-size=2048
      FORCE_COLOR: 0
      CI: true
      # Disable analytics in CI
      VERCEL_ANALYTICS_DEBUG: false
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Verify Node.js version
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"

      - name: Install dependencies
        run: npm ci
        
      - name: Verify test environment
        run: |
          echo "Testing environment setup..."
          node -e "console.log('Node.js can run basic scripts')"
          npm list vitest happy-dom --depth=0 || echo "Dependencies check completed"

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build application
        run: npm run build

      - name: Run test coverage
        run: npm run test:coverage
        continue-on-error: true

      # This step will fail the workflow if any of the above steps failed
      - name: Quality gate passed
        run: echo "✅ All quality checks passed! Ready for deployment."

  # Optional: Add a status check that Vercel can depend on
  deployment-ready:
    name: Deployment Ready
    runs-on: ubuntu-latest
    needs: quality-gate
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Mark as deployment ready
        run: echo "🚀 Main branch is ready for deployment"
